# 网站标题
logo_title: Hexo-Coder
# 初始化风格 black/light
style: black

# 首页URL
link: https://www.liuxunzhuo.top

#标语:
words: AI 🤖️ Code 🧑‍💻 Life 🌈

# 你的昵称
author: LiuXunzhuo
# 中心图标选择男女或者自定义
gender: /img/male.png #/img/female.png

favicon: /img/favicon.ico

# 文章页打赏方式图片(图片路径或链接)
alipay: /img/alipay.jpg #http://dl.weic96.cn/logo.png
wechat: /img/wechat.jpg #http://dl.weic96.cn/logo.png
qq: /img/qq.jpg #http://dl.weic96.cn/logo.png

# 菜单栏配置
menu:
  关于我👀: /about
  访问主站🎉: https://liuxunzhuo.tech
  Github🐒: https://github.com/xunzhuo

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: true
  appId: NOsswOncKgc8HOxqo9oxIWlX-gzGzoHsz
  appKey: z1FihjWEbS8uIfUQdmCtK7zz


highlight:
  enable: true